"""
This class defines ALL events generated by the Azrael v1 contract.

Event List: Lent, Rented, Returned, LendingStopped, CollateralClaimed
"""

from abc import ABC
from dataclasses import dataclass


@dataclass
class AzraelEvent(ABC):
    """
    Abstract Azrael v1 Event. Holds txHash and txOffset, togther they are a unique 
    identifier for azrael events.
    """

    # pylint: disable=invalid-name
    txHash: str
    txOffset: int

    @staticmethod
    def parse_id(_id: str):
        """
        Parses '_id' to txHash and txOffset.

        Args:
            _id (str): mongodb '_id'
            e.i. 0xf79edc5500218427d22d4215799fb51064c633ca919c0406b830ed5dc3c6eb1a_100

        Returns:
            str: txHash
            int: txOffset
        """
        _id = _id.split('_')

        return _id[0], int(_id[1])


@dataclass
class LentEvent(AzraelEvent):
    """
    LentEvent DTO

    Holds the event data for azrael v1 'Lent' event.
    """

    # pylint: disable=invalid-name,too-many-instance-attributes
    lendingId: int
    lentAmount: int
    maxRentDuration: int
    paymentToken: int
    nftAddress: str
    tokenId: str
    lendersAddress: str
    dailyRentPrice: float
    nftPrice: float
    isERC721: bool
    paymentToken: int

    @classmethod
    def from_doc(cls, doc):
        """
        Parses a mongodb document into a 'Lent' Azrael v1 event.

        Args:
            doc (Dict): a mongodb document

        Returns:
            _type_: instance of this class with the correct
            configs.
        """

        txHash, txOffset = AzraelEvent.parse_id(doc['_id'])

        return cls(
            txHash,
            txOffset,
            lendingId=int(doc['lendingId']), 
            lentAmount=int(doc['lentAmount']), 
            maxRentDuration=int(doc['maxRentDuration']),
            paymentToken=int(doc['paymentToken']),
            nftAddress=doc['nftAddress'],
            tokenId=doc['tokenId'],
            lendersAddress=doc['lendersAddress'],
            dailyRentPrice=doc['dailyRentPrice'],
            nftPrice=doc['nftPrice'],
            isERC721=doc['isERC721'],
            )


@dataclass
class RentedEvent(AzraelEvent):
    """
    RentedEvent DTO

    Holds the event data for azrael v1 'Rented' event.
    """

    # pylint: disable=invalid-name
    lendingId: int
    renterAddress: str
    rentDuration: int
    rentedAt: int

    @classmethod
    def from_doc(cls, doc):
        """
        Parses a mongodb document into a 'Rented' Azrael v1 event.

        Args:
            doc (Dict): a mongodb document

        Returns:
            _type_: instance of this class with the correct
            configs.
        """

        txHash, txOffset = AzraelEvent.parse_id(doc['_id'])

        return cls(
            txHash,
            txOffset,
            lendingId=int(doc['lendingId']),
            renterAddress=doc['renterAddress'],
            rentDuration=int(doc['rentDuration']),
            rentedAt=int(doc['rentedAt'])
        )


@dataclass
class ReturnedEvent(AzraelEvent):
    """
    ReturnedEvent DTO

    Holds the event data for azrael v1 'Returned' event.
    """

    #pylint: disable=invalid-name
    lendingId: int
    returnedAt: int

    @classmethod
    def from_doc(cls, doc):
        """
        Parses a mongodb document into a 'Returned' Azrael v1 event.

        Args:
            doc (Dict): a mongodb document

        Returns:
            _type_: instance of this class with the correct
            configs.
        """

        txHash, txOffset = AzraelEvent.parse_id(doc['_id'])

        return cls(
            txHash,
            txOffset,
            lendingId=int(doc['lendingId']),
            returnedAt=int(doc['returnedAt'])
        )

@dataclass
class LendingStoppedEvent(AzraelEvent):
    """
    LendingStopped DTO

    Holds the event data for azrael v1 'LendingStopped' event.
    """

    #pylint: disable=invalid-name
    lendingId: int
    stoppedAt: int

    @classmethod
    def from_doc(cls, doc):
        """
        Parses a mongodb document into a 'LendingStopped' Azrael v1 event.

        Args:
            doc (Dict): a mongodb document

        Returns:
            _type_: instance of this class with the correct
            configs.
        """

        txHash, txOffset = AzraelEvent.parse_id(doc['_id'])

        return cls(
            txHash,
            txOffset,
            lendingId=int(doc['lendingId']),
            stoppedAt=int(doc['stoppedAt'])
        )

@dataclass
class CollateralClaimedEvent(AzraelEvent):
    """
    CollateralClaimed DTO

    Holds the event data for azrael v1 'CollateralClaimed' event.
    """

    #pylint: disable=invalid-name
    lendingId: int
    claimedAt: int

    @classmethod
    def from_doc(cls, doc):
        """
        Parses a mongodb document into a 'CollateralClaimed' Azrael v1 event.

        Args:
            doc (Dict): a mongodb document

        Returns:
            _type_: instance of this class with the correct
            configs.
        """

        txHash, txOffset = AzraelEvent.parse_id(doc['_id'])

        return cls(
            txHash,
            txOffset,
            lendingId=int(doc['lendingId']),
            claimedAt=int(doc['claimedAt'])
        )
